# This workflow tests Sqitch's Snowflake engine. It runs for pushes and pull
# requests on the `main`, `develop`, `**snowflake**`, and `**engine**` branches.
name: ❄️ Snowflake
on:
  push:
    branches: [main, develop, "**engine**", "**snowflake**" ]
  pull_request:
    branches: [main, develop, "**engine**", "**snowflake**" ]
jobs:
  Snowflake:
    name: ❄️ Snowflake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Clients
        run: .github/ubuntu/snowflake.sh
      - name: Setup Perl
        id: perl
        uses: shogo82148/actions-setup-perl@v1
        with: { perl-version: latest }
      - name: Cache CPAN Modules
        uses: actions/cache@v3
        with:
          path: local
          key: perl-${{ steps.perl.outputs.perl-hash }}
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends --cpanfile dist/cpanfile
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends DBD::ODBC
      - name: prove
        env:
          PERL5LIB: "${{ github.workspace }}/local/lib/perl5"
          LIVE_SNOWFLAKE_REQUIRED: true
          SQITCH_TEST_SNOWFLAKE_URI: db:snowflake://${{ secrets.SNOWFLAKE_USERNAME }}:${{ secrets.SNOWFLAKE_PASSWORD }}@sra81677.us-east-1/sqitchtest?Driver=Snowflake;warehouse=compute_wh
        run: prove -lvr t/snowflake.t
